Repository MyPill2023/MyPill, pull requests merged in 2023-08, with the labels that each got.

#203 Refactor : 8회차 - Order
  src/main/java/com/mypill/domain/buyer/controller/BuyerController.java
  src/main/java/com/mypill/domain/buyer/dto/response/MyOrderResponse.java
  src/main/java/com/mypill/domain/cart/controller/CartController.java
  src/main/java/com/mypill/domain/cart/entity/Cart.java
  src/main/java/com/mypill/domain/cart/entity/CartProduct.java
  src/main/java/com/mypill/domain/cart/repository/CartProductRepository.java
  src/main/java/com/mypill/domain/cart/service/CartService.java
  src/main/java/com/mypill/domain/notification/entity/Notification.java
  src/main/java/com/mypill/domain/notification/event/NotificationEventListener.java
  src/main/java/com/mypill/domain/notification/service/NotificationService.java
  src/main/java/com/mypill/domain/order/controller/OrderController.java
  src/main/java/com/mypill/domain/order/dto/response/OrderManagementResponse.java
  src/main/java/com/mypill/domain/order/dto/response/PayResponse.java
  src/main/java/com/mypill/domain/order/entity/Order.java
  src/main/java/com/mypill/domain/order/entity/OrderItem.java
  src/main/java/com/mypill/domain/order/entity/OrderStatus.java
  src/main/java/com/mypill/domain/order/repository/OrderItemRepository.java
  src/main/java/com/mypill/domain/order/repository/OrderItemRepositoryCustom.java
  src/main/java/com/mypill/domain/order/repository/OrderItemRepositoryImpl.java
  src/main/java/com/mypill/domain/order/repository/OrderRepository.java
  src/main/java/com/mypill/domain/order/repository/OrderRepositoryImpl.java
  src/main/java/com/mypill/domain/order/service/OrderService.java
  src/main/java/com/mypill/domain/order/service/TossPaymentService.java
  src/main/java/com/mypill/domain/product/controller/ProductController.java
  src/main/java/com/mypill/domain/product/service/ProductService.java
  src/main/java/com/mypill/domain/seller/controller/SellerController.java
  src/main/java/com/mypill/global/event/EventAfterOrderChanged.java
  src/main/java/com/mypill/global/initdata/NotProd.java
  src/main/java/com/mypill/global/rq/Rq.java
  src/main/resources/templates/usr/buyer/myOrder.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/notification/list.html
  src/main/resources/templates/usr/order/detail.html
  src/main/resources/templates/usr/order/fail.html
  src/main/resources/templates/usr/order/form.html
  src/main/resources/templates/usr/order/management.html
  src/main/resources/templates/usr/product/detail.html
  src/main/resources/templates/usr/seller/orderList.html
  src/test/java/com/mypill/domain/cart/service/CartServiceTests.java
  src/test/java/com/mypill/domain/order/controller/OrderControllerTests.java
  src/test/java/com/mypill/domain/order/service/OrderServiceTests.java
Labels: refactor

#205 Fix : 설문 기능 버그 수정
  src/main/java/com/mypill/domain/cart/dto/response/CartProductResponse.java
  src/main/java/com/mypill/domain/cart/dto/response/CartResponse.java
  src/main/java/com/mypill/domain/cart/entity/Cart.java
  src/main/java/com/mypill/domain/cart/repository/CartProductRepository.java
  src/main/java/com/mypill/domain/cart/service/CartService.java
  src/main/java/com/mypill/domain/email/controller/EmailVerificationController.java
  src/main/java/com/mypill/domain/home/controller/HomeController.java
  src/main/java/com/mypill/domain/member/controller/MemberController.java
  src/main/java/com/mypill/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/mypill/global/security/SecurityConfig.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/survey/step.html
  src/test/java/com/mypill/domain/home/controller/HomeControllerTest.java
Labels: bug, enhancement, refactor

#208 Fix : 상품 좋아요 로직 변경
  src/main/java/com/mypill/domain/buyer/controller/BuyerController.java
  src/main/java/com/mypill/domain/cart/entity/CartProduct.java
  src/main/java/com/mypill/domain/cart/repository/CartRepository.java
  src/main/java/com/mypill/domain/diary/controller/DiaryController.java
  src/main/java/com/mypill/domain/email/controller/EmailVerificationController.java
  src/main/java/com/mypill/domain/home/controller/HomeController.java
  src/main/java/com/mypill/domain/member/controller/MemberController.java
  src/main/java/com/mypill/domain/member/entity/Member.java
  src/main/java/com/mypill/domain/member/service/MemberService.java
  src/main/java/com/mypill/domain/notification/entity/NotificationTypeCode.java
  src/main/java/com/mypill/domain/notification/service/NotificationService.java
  src/main/java/com/mypill/domain/order/entity/Order.java
  src/main/java/com/mypill/domain/product/controller/ProductController.java
  src/main/java/com/mypill/domain/product/entity/Product.java
  src/main/java/com/mypill/domain/product/event/ProductEventListener.java
  src/main/java/com/mypill/domain/product/repository/ProductRepository.java
  src/main/java/com/mypill/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/mypill/domain/product/service/ProductService.java
  src/main/java/com/mypill/domain/productlike/controller/ProductLikeController.java
  src/main/java/com/mypill/domain/productlike/entity/ProductLike.java
  src/main/java/com/mypill/domain/productlike/repository/ProductLikeRepository.java
  src/main/java/com/mypill/domain/productlike/service/ProductLikeService.java
  src/main/java/com/mypill/global/event/EventAfterLike.java
  src/main/java/com/mypill/global/event/EventAfterUnlike.java
  src/main/java/com/mypill/global/security/SecurityConfig.java
  src/main/resources/templates/usr/buyer/myLikes.html
  src/main/resources/templates/usr/cart/list.html
  src/main/resources/templates/usr/diary/checklist.html
  src/main/resources/templates/usr/diary/list.html
  src/main/resources/templates/usr/home/main.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/join.html
  src/main/resources/templates/usr/member/myPage.html
  src/main/resources/templates/usr/notification/list.html
  src/main/resources/templates/usr/order/detail.html
  src/main/resources/templates/usr/order/form.html
  src/main/resources/templates/usr/order/management.html
  src/main/resources/templates/usr/product/detail.html
  src/main/resources/templates/usr/product/list.html
  src/main/resources/templates/usr/seller/myProduct.html
  src/test/java/com/mypill/domain/buyer/controller/BuyerControllerTest.java
  src/test/java/com/mypill/domain/home/controller/HomeControllerTest.java
  src/test/java/com/mypill/domain/member/service/MemberServiceTest.java
Labels: bug, enhancement, refactor

#210 Enhancement/209
  src/main/java/com/mypill/domain/buyer/controller/BuyerController.java
  src/main/java/com/mypill/domain/category/dto/response/CategoryResponse.java
  src/main/java/com/mypill/domain/home/controller/HomeController.java
  src/main/java/com/mypill/domain/nutrient/dto/response/NutrientResponse.java
  src/main/java/com/mypill/domain/post/dto/response/PostResponse.java
  src/main/java/com/mypill/domain/product/controller/ProductController.java
  src/main/java/com/mypill/domain/product/dto/response/ProductPageResponse.java
  src/main/java/com/mypill/domain/product/dto/response/ProductResponse.java
  src/main/java/com/mypill/domain/product/dto/response/ProductsResponse.java
  src/main/java/com/mypill/global/initdata/NotProd.java
  src/main/resources/templates/usr/buyer/myLikes.html
  src/main/resources/templates/usr/home/main.html
  src/main/resources/templates/usr/post/detail.html
  src/main/resources/templates/usr/post/list.html
  src/main/resources/templates/usr/post/update.html
  src/main/resources/templates/usr/product/detail.html
  src/main/resources/templates/usr/product/list.html
  src/main/resources/templates/usr/product/update.html
Labels: enhancement, refactor

#215 Refactor : DTO 수정 (Cart, Comment, Post)
  src/main/java/com/mypill/domain/cart/dto/response/CartProductResponse.java
  src/main/java/com/mypill/domain/cart/dto/response/CartResponse.java
  src/main/java/com/mypill/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/mypill/domain/comment/dto/response/CommentsResponse.java
  src/main/java/com/mypill/domain/member/controller/MemberController.java
  src/main/java/com/mypill/domain/post/dto/response/PostResponse.java
  src/main/java/com/mypill/domain/post/dto/response/PostsResponse.java
  src/main/resources/templates/usr/cart/list.html
  src/main/resources/templates/usr/member/myComments.html
  src/main/resources/templates/usr/member/myPosts.html
  src/main/resources/templates/usr/post/detail.html
Labels: refactor

#212 Refactor : DTO 수정 (Order, Notification)
  src/main/java/com/mypill/domain/buyer/dto/response/MyOrderResponse.java
  src/main/java/com/mypill/domain/notification/controller/NotificationController.java
  src/main/java/com/mypill/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/mypill/domain/notification/dto/response/NotificationsResponse.java
  src/main/java/com/mypill/domain/notification/entity/Notification.java
  src/main/java/com/mypill/domain/order/dto/response/OrderItemResponse.java
  src/main/java/com/mypill/domain/order/dto/response/OrderManagementResponse.java
  src/main/java/com/mypill/domain/seller/dto/OrderManagementResponse.java
  src/main/resources/templates/usr/buyer/myOrder.html
  src/main/resources/templates/usr/notification/list.html
  src/main/resources/templates/usr/order/detail.html
  src/main/resources/templates/usr/order/form.html
  src/main/resources/templates/usr/order/management.html
  src/main/resources/templates/usr/seller/orderList.html
Labels: refactor

#216 Refactor: DTO 수정 (Diary)
  src/main/java/com/mypill/domain/category/dto/response/CategoriesResponse.java
  src/main/java/com/mypill/domain/comment/dto/response/CommentsResponse.java
  src/main/java/com/mypill/domain/diary/controller/DiaryController.java
  src/main/java/com/mypill/domain/diary/dto/response/DiaryCheckListResponse.java
  src/main/java/com/mypill/domain/diary/dto/response/DiaryCheckLogResponse.java
  src/main/java/com/mypill/domain/diary/dto/response/DiaryListResponse.java
  src/main/java/com/mypill/domain/diary/dto/response/DiaryResponse.java
  src/main/java/com/mypill/domain/order/dto/response/OrderResponse.java
  src/main/java/com/mypill/domain/post/dto/response/PostResponse.java
  src/main/java/com/mypill/domain/question/dto/response/QuestionResponse.java
  src/main/java/com/mypill/domain/survey/controller/SurveyController.java
  src/main/java/com/mypill/domain/survey/dto/response/StepResponse.java
  src/main/resources/templates/usr/diary/checklist.html
  src/main/resources/templates/usr/diary/create.html
  src/main/resources/templates/usr/diary/list.html
  src/main/resources/templates/usr/post/detail.html
  src/main/resources/templates/usr/survey/start.html
  src/main/resources/templates/usr/survey/step.html
  src/test/java/com/mypill/domain/post/service/PostServiceTest.java
Labels: refactor
